// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: Anokino (https://sketchfab.com/Anokino)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/mazda-rx-7-car-404b2aefdf084f01bc3d75559c9c4088
// Title: Mazda RX-7 (Car)
// */

// import React, { useRef } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'

// export default function Car(props) {
//   const group = useRef()
//   const { nodes, materials, animations } = useGLTF('/mazda_rx-7_car.glb')
//   const { actions } = useAnimations(animations, group)
//   return (

//     <group ref={group} {...props} dispose={null}>
//       <group name="Sketchfab_Scene">
//         <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.767}>
//           <group name="root">
//             <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
//               <group name="Empty004_1" position={[2.048, -0.684, 1.906]} scale={0.027}>
//                 <group
//                   name="Plane001_0"
//                   position={[-16.033, -0.884, -40.345]}
//                   rotation={[0.612, 0, 0]}
//                   scale={1.496}>
//                   <mesh
//                     name="Object_5"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Object_5.geometry}
//                     material={materials['Material.009']}
//                   />
//                   <mesh
//                     name="Object_6"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Object_6.geometry}
//                     material={materials['Material.002']}
//                   />
//                   <mesh
//                     name="Object_7"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Object_7.geometry}
//                     material={materials['Material.006']}
//                   />
//                   <mesh
//                     name="Object_8"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Object_8.geometry}
//                     material={materials['Material.007']}
//                   />
//                 </group>
//               </group>
//               <group
//                 name="Plane_2"
//                 position={[1.623, -0.708, 0.834]}
//                 rotation={[0.612, 0, 0]}
//                 scale={0.04}>
//                 <mesh
//                   name="Object_10"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_10.geometry}
//                   material={materials['Material.007']}
//                 />
//                 <mesh
//                   name="Object_11"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_11.geometry}
//                   material={materials['Material.003']}
//                 />
//                 <mesh
//                   name="Object_12"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_12.geometry}
//                   material={materials['Material.006']}
//                 />
//                 <mesh
//                   name="Object_13"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_13.geometry}
//                   material={materials['Material.008']}
//                 />
//                 <mesh
//                   name="Object_14"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_14.geometry}
//                   material={materials['Material.009']}
//                 />
//                 <mesh
//                   name="Object_15"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_15.geometry}
//                   material={materials['Material.016']}
//                 />
//                 <mesh
//                   name="Object_16"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_16.geometry}
//                   material={materials['Material.017']}
//                 />
//                 <mesh
//                   name="Object_17"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_17.geometry}
//                   material={materials['Material.018']}
//                 />
//                 <mesh
//                   name="Object_18"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_18.geometry}
//                   material={materials['Material.019']}
//                 />
//                 <mesh
//                   name="Object_19"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_19.geometry}
//                   material={materials.Material}
//                 />
//               </group>
//               <group
//                 name="Plane004_3"
//                 position={[1.623, -0.708, 0.834]}
//                 rotation={[0.612, 0, 0]}
//                 scale={0.04}>
//                 <mesh
//                   name="Object_21"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_21.geometry}
//                   material={materials['Material.001']}
//                 />
//                 <mesh
//                   name="Object_22"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_22.geometry}
//                   material={materials['Material.005']}
//                 />
//               </group>
//               <group
//                 name="Cylinder003_4"
//                 position={[1.248, -0.963, -0.447]}
//                 rotation={[1.532, 0, 0]}
//                 scale={0.026}>
//                 <mesh
//                   name="Object_24"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_24.geometry}
//                   material={materials['Material.001']}
//                 />
//               </group>
//               <group
//                 name="Circle008_5"
//                 position={[1.078, -0.94, 1.714]}
//                 rotation={[-2.511, 0, -Math.PI / 2]}
//                 scale={0.172}>
//                 <mesh
//                   name="Object_26"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_26.geometry}
//                   material={materials['Material.011']}
//                 />
//                 <mesh
//                   name="Object_27"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_27.geometry}
//                   material={materials['Material.014']}
//                 />
//                 <mesh
//                   name="Object_28"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_28.geometry}
//                   material={materials['Material.015']}
//                 />
//               </group>
//               <group
//                 name="Circle009_6"
//                 position={[2.168, -0.94, 1.714]}
//                 rotation={[-0.63, 0, Math.PI / 2]}
//                 scale={0.172}>
//                 <mesh
//                   name="Object_30"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_30.geometry}
//                   material={materials['Material.011']}
//                 />
//                 <mesh
//                   name="Object_31"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_31.geometry}
//                   material={materials['Material.014']}
//                 />
//                 <mesh
//                   name="Object_32"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_32.geometry}
//                   material={materials['Material.015']}
//                 />
//               </group>
//               <group
//                 name="Circle010_7"
//                 position={[1.078, -0.94, 0.072]}
//                 rotation={[-2.511, 0, -Math.PI / 2]}
//                 scale={0.172}>
//                 <mesh
//                   name="Object_34"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_34.geometry}
//                   material={materials['Material.011']}
//                 />
//                 <mesh
//                   name="Object_35"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_35.geometry}
//                   material={materials['Material.014']}
//                 />
//                 <mesh
//                   name="Object_36"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_36.geometry}
//                   material={materials['Material.015']}
//                 />
//               </group>
//               <group
//                 name="Circle011_8"
//                 position={[2.168, -0.94, 0.072]}
//                 rotation={[-0.63, 0, Math.PI / 2]}
//                 scale={0.172}>
//                 <mesh
//                   name="Object_38"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_38.geometry}
//                   material={materials['Material.011']}
//                 />
//                 <mesh
//                   name="Object_39"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_39.geometry}
//                   material={materials['Material.014']}
//                 />
//                 <mesh
//                   name="Object_40"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_40.geometry}
//                   material={materials['Material.015']}
//                 />
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/mazda_rx-7_car.glb')

const Car = () => {
  return <div>Car</div>;
};

export default Car;
